import pandas as pd
path="C:\\Users\\Michael\\Downloads\\ACS_NSQIP18.txt"
data = pd.read_csv(path, sep="\t")

s = ""

for i in range(len(data.columns)):
    s += data.columns[i] + " "
    if data.dtypes[i] == "object":
        s += "varchar(255)" + ",\n"
    if data.dtypes[i] == "int64":
        s += "int" + ",\n"
    if data.dtypes[i] == "float64":
        s += "double precision" + ",\n"
  

data.to_csv('nsqip.txt', index=False,na_rep = 'NULL')
print(data.head)



'''

CREATE TABLE NSQIP_data(
PUFYEAR int,
CaseID int,
SEX varchar(255),
RACE_NEW varchar(255),
ETHNICITY_HISPANIC varchar(255),
PRNCPTX varchar(255),
CPT int,
WORKRVU double precision,
INOUT varchar(255),
TRANST varchar(255),
Age varchar(255),
AdmYR int,
OperYR int,
DISCHDEST varchar(255),
ANESTHES varchar(255),
SURGSPEC varchar(255),
ELECTSURG varchar(255),
HEIGHT int,
WEIGHT int,
DIABETES varchar(255),
SMOKE varchar(255),
DYSPNEA varchar(255),
FNSTATUS2 varchar(255),
VENTILAT varchar(255),
HXCOPD varchar(255),
ASCITES varchar(255),
HXCHF varchar(255),
HYPERMED varchar(255),
RENAFAIL varchar(255),
DIALYSIS varchar(255),
DISCANCR varchar(255),
WNDINF varchar(255),
STEROID varchar(255),
WTLOSS varchar(255),
BLEEDDIS varchar(255),
TRANSFUS varchar(255),
PRSEPIS varchar(255),
DPRNA int,
DPRBUN int,
DPRCREAT int,
DPRALBUM int,
DPRBILI int,
DPRSGOT int,
DPRALKPH int,
DPRWBC int,
DPRHCT int,
DPRPLATE int,
DPRPTT int,
DPRPT int,
DPRINR int,
PRSODM double precision,
PRBUN double precision,
PRCREAT double precision,
PRALBUM double precision,
PRBILI double precision,
PRSGOT double precision,
PRALKPH double precision,
PRWBC double precision,
PRHCT double precision,
PRPLATE double precision,
PRPTT double precision,
PRINR double precision,
PRPT int,
OTHERPROC1 varchar(255),
OTHERCPT1 varchar(255),
OTHERWRVU1 double precision,
OTHERPROC2 varchar(255),
OTHERCPT2 varchar(255),
OTHERWRVU2 double precision,
OTHERPROC3 varchar(255),
OTHERCPT3 varchar(255),
OTHERWRVU3 double precision,
OTHERPROC4 varchar(255),
OTHERCPT4 varchar(255),
OTHERWRVU4 double precision,
OTHERPROC5 varchar(255),
OTHERCPT5 varchar(255),
OTHERWRVU5 double precision,
OTHERPROC6 varchar(255),
OTHERCPT6 varchar(255),
OTHERWRVU6 double precision,
OTHERPROC7 varchar(255),
OTHERCPT7 varchar(255),
OTHERWRVU7 double precision,
OTHERPROC8 varchar(255),
OTHERCPT8 varchar(255),
OTHERWRVU8 double precision,
OTHERPROC9 varchar(255),
OTHERCPT9 varchar(255),
OTHERWRVU9 double precision,
OTHERPROC10 varchar(255),
OTHERCPT10 double precision,
OTHERWRVU10 double precision,
CONCURR1 varchar(255),
CONCPT1 varchar(255),
CONWRVU1 double precision,
CONCURR2 varchar(255),
CONCPT2 varchar(255),
CONWRVU2 double precision,
CONCURR3 varchar(255),
CONCPT3 varchar(255),
CONWRVU3 double precision,
CONCURR4 varchar(255),
CONCPT4 varchar(255),
CONWRVU4 double precision,
CONCURR5 varchar(255),
CONCPT5 double precision,
CONWRVU5 double precision,
CONCURR6 varchar(255),
CONCPT6 varchar(255),
CONWRVU6 double precision,
CONCURR7 varchar(255),
CONCPT7 double precision,
CONWRVU7 double precision,
CONCURR8 varchar(255),
CONCPT8 double precision,
CONWRVU8 double precision,
CONCURR9 varchar(255),
CONCPT9 double precision,
CONWRVU9 double precision,
CONCURR10 varchar(255),
CONCPT10 double precision,
CONWRVU10 double precision,
EMERGNCY varchar(255),
WNDCLAS varchar(255),
ASACLAS varchar(255),
MORTPROB double precision,
MORBPROB double precision,
OPTIME int,
HDISDT int,
YRDEATH int,
TOTHLOS int,
AdmQtr int,
HtoODay double precision,
NSUPINFEC int,
SUPINFEC varchar(255),
SSSIPATOS varchar(255),
DSUPINFEC int,
NWNDINFD int,
WNDINFD varchar(255),
DSSIPATOS varchar(255),
DWNDINFD int,
NORGSPCSSI int,
ORGSPCSSI varchar(255),
OSSIPATOS varchar(255),
DORGSPCSSI int,
NDEHIS int,
DEHIS varchar(255),
DDEHIS int,
NOUPNEUMO int,
OUPNEUMO varchar(255),
PNAPATOS varchar(255),
DOUPNEUMO int,
NREINTUB int,
REINTUB varchar(255),
DREINTUB int,
NPULEMBOL int,
PULEMBOL varchar(255),
DPULEMBOL int,
NFAILWEAN int,
FAILWEAN varchar(255),
VENTPATOS varchar(255),
DFAILWEAN int,
NRENAINSF int,
RENAINSF varchar(255),
DRENAINSF int,
NOPRENAFL int,
OPRENAFL varchar(255),
DOPRENAFL int,
NURNINFEC int,
URNINFEC varchar(255),
UTIPATOS varchar(255),
DURNINFEC int,
NCNSCVA int,
CNSCVA varchar(255),
DCNSCVA int,
NCDARREST int,
CDARREST varchar(255),
DCDARREST int,
NCDMI int,
CDMI varchar(255),
DCDMI int,
NOTHBLEED int,
OTHBLEED varchar(255),
DOTHBLEED int,
NOTHDVT int,
OTHDVT varchar(255),
DOTHDVT int,
NOTHSYSEP int,
OTHSYSEP varchar(255),
SEPSISPATOS varchar(255),
DOTHSYSEP int,
NOTHSESHOCK int,
OTHSESHOCK varchar(255),
SEPSHOCKPATOS varchar(255),
DOTHSESHOCK int,
PODIAG double precision,
PODIAGTX double precision,
PODIAG10 varchar(255),
PODIAGTX10 varchar(255),
RETURNOR varchar(255),
DOpertoD int,
DOptoDis int,
STILLINHOSP varchar(255),
REOPERATION1 varchar(255),
RETORPODAYS int,
REOPORCPT1 varchar(255),
RETORRELATED varchar(255),
REOPORICD91 double precision,
REOPOR1ICD101 varchar(255),
REOPERATION2 varchar(255),
RETOR2PODAYS int,
REOPOR2CPT1 varchar(255),
RETOR2RELATED varchar(255),
REOPOR2ICD91 double precision,
REOPOR2ICD101 varchar(255),
REOPERATION3 varchar(255),
READMISSION1 varchar(255),
READMPODAYS1 int,
UNPLANNEDREADMISSION1 varchar(255),
READMRELATED1 varchar(255),
READMSUSPREASON1 varchar(255),
READMUNRELSUSP1 varchar(255),
READMRELICD91 double precision,
READMRELICD101 varchar(255),
READMUNRELICD91 double precision,
READMUNRELICD101 varchar(255),
READMISSION2 varchar(255),
READMPODAYS2 int,
UNPLANNEDREADMISSION2 varchar(255),
READMRELATED2 varchar(255),
READMSUSPREASON2 varchar(255),
READMUNRELSUSP2 double precision,
READMRELICD92 double precision,
READMRELICD102 varchar(255),
READMUNRELICD92 double precision,
READMUNRELICD102 double precision,
READMISSION3 varchar(255),
READMPODAYS3 int,
UNPLANNEDREADMISSION3 varchar(255),
READMRELATED3 varchar(255),
READMSUSPREASON3 varchar(255),
READMUNRELSUSP3 double precision,
READMRELICD93 double precision,
READMRELICD103 varchar(255),
READMUNRELICD93 double precision,
READMUNRELICD103 double precision,
READMISSION4 varchar(255),
READMPODAYS4 int,
UNPLANNEDREADMISSION4 varchar(255),
READMRELATED4 varchar(255),
READMSUSPREASON4 varchar(255),
READMUNRELSUSP4 double precision,
READMRELICD94 double precision,
READMRELICD104 varchar(255),
READMUNRELICD94 double precision,
READMUNRELICD104 double precision,
READMISSION5 varchar(255),
READMPODAYS5 int,
UNPLANNEDREADMISSION5 varchar(255),
READMRELATED5 varchar(255),
READMSUSPREASON5 varchar(255),
READMUNRELSUSP5 double precision,
READMRELICD95 double precision,
READMRELICD105 varchar(255),
READMUNRELICD95 double precision,
READMUNRELICD105 double precision,
WOUND_CLOSURE varchar(255),
PODIAG_OTHER double precision,
PODIAG_OTHER10 varchar(255),
ANESTHES_OTHER varchar(255),
OTHCDIFF varchar(255),
NOTHCDIFF int,
DOTHCDIFF int,
)

\COPY nsqip_data FROM 'C:\\Users\\Michael\\Documents\\NSQIPviewer\\BACKEND\\nsqip.txt' with delimiter ',' NULL AS 'NULL' CSV header

'''