import pandas as pd
path="C:\\Users\\Michael\\Documents\\nsqip\\ACS_NSQIP10.txt"

data = pd.read_csv(path, sep="\t",encoding='cp1252')

s = ""

for i in range(len(data.columns)):
    s += data.columns[i] + " "
    if data.dtypes[i] == "object":
        s += "varchar(255)" + ",\n"
    if data.dtypes[i] == "int64":
        s += "int" + ",\n"
    if data.dtypes[i] == "float64":
        s += "double precision" + ",\n"

  
print(s)



'''

CREATE TABLE NSQIP2010(
CaseID int,
SEX varchar(255),
RACE_NEW varchar(255),
ETHNICITY_HISPANIC varchar(255),
PRNCPTX varchar(255),
CPT varchar(255),
WORKRVU double precision,
INOUT varchar(255),
TRANST varchar(255),
Age varchar(255),
AdmYR int,
AdmSYR int,
OperYR int,
ANESTHES varchar(255),
ATTEND varchar(255),
SURGSPEC varchar(255),
HEIGHT int,
WEIGHT int,
DIABETES varchar(255),
SMOKE varchar(255),
PACKS int,
ETOH varchar(255),
DYSPNEA varchar(255),
DNR varchar(255),
FNSTATUS1 double precision,
FNSTATUS2 varchar(255),
VENTILAT varchar(255),
HXCOPD varchar(255),
CPNEUMON varchar(255),
ASCITES varchar(255),
ESOVAR varchar(255),
HXCHF varchar(255),
HXMI varchar(255),
PRVPCI varchar(255),
PRVPCS varchar(255),
HXANGINA varchar(255),
HYPERMED varchar(255),
HXPVD varchar(255),
RESTPAIN varchar(255),
RENAFAIL varchar(255),
DIALYSIS varchar(255),
IMPSENS varchar(255),
COMA varchar(255),
HEMI varchar(255),
HXTIA varchar(255),
CVA varchar(255),
CVANO varchar(255),
TUMORCNS varchar(255),
Para varchar(255),
QUAD varchar(255),
DISCANCR varchar(255),
WNDINF varchar(255),
STEROID varchar(255),
WTLOSS varchar(255),
BLEEDDIS varchar(255),
TRANSFUS varchar(255),
CHEMO varchar(255),
RADIO varchar(255),
PRSEPIS varchar(255),
Pregnancy varchar(255),
PrOper30 varchar(255),
DPRNA int,
DPRBUN int,
DPRCREAT int,
DPRALBUM int,
DPRBILI int,
DPRSGOT int,
DPRALKPH int,
DPRWBC int,
DPRHCT int,
DPRPLATE int,
DPRPTT int,
DPRPT int,
DPRINR int,
PRSODM double precision,
PRBUN double precision,
PRCREAT double precision,
PRALBUM double precision,
PRBILI double precision,
PRSGOT double precision,
PRALKPH double precision,
PRWBC double precision,
PRHCT double precision,
PRPLATE double precision,
PRPTT double precision,
PRINR double precision,
PRPT double precision,
OTHERPROC1 varchar(255),
OTHERCPT1 varchar(255),
OTHERWRVU1 double precision,
OTHERPROC2 varchar(255),
OTHERCPT2 varchar(255),
OTHERWRVU2 double precision,
OTHERPROC3 varchar(255),
OTHERCPT3 varchar(255),
OTHERWRVU3 double precision,
OTHERPROC4 varchar(255),
OTHERCPT4 varchar(255),
OTHERWRVU4 double precision,
OTHERPROC5 varchar(255),
OTHERCPT5 varchar(255),
OTHERWRVU5 double precision,
OTHERPROC6 varchar(255),
OTHERCPT6 varchar(255),
OTHERWRVU6 double precision,
OTHERPROC7 varchar(255),
OTHERCPT7 varchar(255),
OTHERWRVU7 double precision,
OTHERPROC8 varchar(255),
OTHERCPT8 varchar(255),
OTHERWRVU8 double precision,
OTHERPROC9 varchar(255),
OTHERCPT9 double precision,
OTHERWRVU9 double precision,
OTHERPROC10 varchar(255),
OTHERCPT10 double precision,
OTHERWRVU10 double precision,
CONCURR1 varchar(255),
CONCPT1 varchar(255),
CONWRVU1 double precision,
CONCURR2 varchar(255),
CONCPT2 varchar(255),
CONWRVU2 double precision,
CONCURR3 varchar(255),
CONCPT3 varchar(255),
CONWRVU3 double precision,
CONCURR4 varchar(255),
CONCPT4 varchar(255),
CONWRVU4 double precision,
CONCURR5 varchar(255),
CONCPT5 varchar(255),
CONWRVU5 double precision,
CONCURR6 varchar(255),
CONCPT6 varchar(255),
CONWRVU6 double precision,
CONCURR7 varchar(255),
CONCPT7 double precision,
CONWRVU7 double precision,
CONCURR8 varchar(255),
CONCPT8 double precision,
CONWRVU8 double precision,
CONCURR9 varchar(255),
CONCPT9 double precision,
CONWRVU9 double precision,
CONCURR10 varchar(255),
CONCPT10 double precision,
CONWRVU10 double precision,
OPNOTE double precision,
PGY int,
EMERGNCY varchar(255),
WNDCLAS varchar(255),
ASACLAS varchar(255),
AIRTRA double precision,
MALLAMP int,
MortProb double precision,
MorbProb double precision,
RBC int,
ANESurg int,
SurgAne int,
DPATRM int,
ANETIME int,
OPTIME int,
TYPEINTOC varchar(255),
SDISDT int,
HDISDT int,
YRDEATH int,
TOTHLOS int,
AdmQtr int,
HtoODAY int,
StoODay int,
TOTSLOS int,
NSUPINFEC int,
SUPINFEC varchar(255),
DSUPINFEC int,
NWNDINFD int,
WNDINFD varchar(255),
DWNDINFD int,
NORGSPCSSI int,
ORGSPCSSI varchar(255),
DORGSPCSSI int,
NDEHIS int,
DEHIS varchar(255),
DDEHIS int,
NOUPNEUMO int,
OUPNEUMO varchar(255),
DOUPNEUMO int,
NREINTUB int,
REINTUB varchar(255),
DREINTUB int,
NPULEMBOL int,
PULEMBOL varchar(255),
DPULEMBOL int,
NFAILWEAN int,
FAILWEAN varchar(255),
DFAILWEAN int,
NRENAINSF int,
RENAINSF varchar(255),
DRENAINSF int,
NOPRENAFL int,
OPRENAFL varchar(255),
DOPRENAFL int,
NURNINFEC int,
URNINFEC varchar(255),
DURNINFEC int,
NCNSCVA int,
CNSCVA varchar(255),
DCNSCVA int,
NCNSCOMA int,
CNSCOMA varchar(255),
DCNSCOMA int,
NNEURODEF int,
NEURODEF varchar(255),
DNEURODEF int,
NCDARREST int,
CDARREST varchar(255),
DCDARREST int,
NCDMI int,
CDMI varchar(255),
DCDMI int,
NOTHBLEED int,
OTHBLEED varchar(255),
DOTHBLEED int,
NOTHGRAFL int,
OTHGRAFL varchar(255),
DOTHGRAFL int,
NOTHDVT int,
OTHDVT varchar(255),
DOTHDVT int,
NOTHSYSEP int,
OTHSYSEP varchar(255),
DOTHSYSEP int,
NOTHSESHOCK int,
OTHSESHOCK varchar(255),
DOTHSESHOCK int,
PODIAG varchar(255),
PODIAGTX varchar(255),
RETURNOR varchar(255),
DSDtoHD int,
DOpertoD int,
DOptoDis int)
'''


